# Generated by Django 5.0.1 on 2024-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=55, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=55, verbose_name="Last name"
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=55, verbose_name="Email"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=55, verbose_name="Subject"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "contact form",
                "verbose_name_plural": "contact forms",
            },
        ),
    ]
