# Generated by Django 5.0.1 on 2024-01-29 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Created at"
            ),
        ),
    ]
